version: "3.9"

services:
  redis:
    image: redis
    container_name: redis-container 
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    command: ["redis-server", "--appendonly", "yes"]